### ISSUE TITLE
bug: setRoot causing scroll freeze

### ISSUE THREAD

**Issue by TylerAHolden** [ionic-team/ionic-framework#18973]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

The bug is rather inconsistent making it hard to debug or find the exact cause. Essentially after selecting an item on an ion-menu to setRoot of a new page, scrolling on ion-content is frozen. This also happens sometimes after slightly opening the menu via swiping and then closing. On developer tools, it appears that the entire ion-app element is being scrolled - almost like ion-app is not passing the touch events down properly.. I'm not very experienced in debugging this type of issue but a live project of the issue can be found at dev.vetgraft.com. I uploaded a screen recording of the issue here: https://drive.google.com/file/d/1EYz-4IRVZxkfEoYGE632T9DEmhh1ZPw4/view?usp=sharing

If there is anything else I should do to help let me know.

NOTE: This ONLY happens on iOS safari from what I can tell so far - ios 12.3.1 iPhoneX to be exact.

Similar to https://github.com/ionic-team/ionic-v3/issues/1003

**Expected behavior:**

To not have a frozen app.

**Steps to reproduce:**

Difficult to find exact replication steps. Use menu to select a different page or slightly open and close the menu via swiping. Sometimes this causes the ion-content to be frozen and refuse scrolling.

**Related code:**

dev.vetgraft.com

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.2.3 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.6.2
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v11.6.0 (/usr/local/bin/node)
   npm    : 6.9.0
   OS     : macOS Mojave
```

**Comment by NG-tylerholden** [comment]
Just noticed that also sometimes tapping and holding for a split second and then trying to scroll will also cause the issue. Again, I really don't know much about what could be going on but it kinda seems like sometimes a touch event listener will get stuck on one of the main elements (ion-app or app-root) or something instead of passing the event down to ion-content so that it can scroll properly.

**Comment by danielsotopino** [comment]
this is happening to me as well, i believe is related to this issue:
https://github.com/ionic-team/ionic-v3/issues/984, they resolved in ionic3 with this:
https://github.com/ionic-team/ionic-v3/pull/989 but haven't found any fix for ionic 4.

I found information on the forums about it, i had to switch the menu to type overlay and add 
```
global.scss
ion-app.ios ion-content {
    pointer-events: auto;
 }
```

And now it works properly.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Are you able to reproduce this issue on any of the Ionic starters or on the Ionic Conference App?

**Comment by NG-tylerholden** [comment]
Yes. You can easily reproduce with the conference app. Here is a link to a screen recording I just made. https://drive.google.com/file/d/1v5lQn_0rJUtb0GXlundts6ZC4DNPaakN/view?usp=sharing
I click on the elements in inspector just to show that the DOM has something scrolling and so you can see that I am, in fact, trying to scroll. This bug still presents itself without devtools open though.

**Comment by NG-tylerholden** [comment]
https://zealous-chandrasekhar-44dc8c.netlify.com is the hosted ionic conference app if you'd like to try it for yourself on an iphone.

**Comment by liamdebeasi** [comment]
Thanks for the follow up. Is this happening on Safari for iOS or when running as a standalone app (i.e. Cordova/Capacitor)?

**Comment by NG-tylerholden** [comment]
safari ios

**Comment by danielsotopino** [comment]
I'm using an iOS app, and having the same issue after navigating a flow of screens and returning to the first screen with setRoot, had to use navigateBack instead.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Is this still an issue with the latest version of Ionic Framework? If so, please provide a repo with the code required to reproduce this issue.
