### ISSUE TITLE
bug: Content in menu does not respect safe area

### ISSUE THREAD

**Issue by mhartington** [ionic-team/ionic-framework#19482]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

When placing an `ion-content` as a direct child of `ion-menu` on iOS, the content area is pushed up into the statusbar area. 

**Expected behavior:**

The content should be pushed down by the safe-area amount.

**Steps to reproduce:**

**Related code:**

```html
<ion-app>
  <div class="ion-page" id="main"></div>
  <ion-menu contentId="main">

    <ion-content>
      <ion-list>
        <ion-item>Item 01</ion-item>
        <ion-item>Item 02</ion-item>
        <ion-item>Item 03</ion-item>
      </ion-list>
    </ion-content>
  </ion-menu>
</ion-app>
```

![IMG_9823](https://user-images.githubusercontent.com/2835826/65804184-0095e400-e14f-11e9-98f8-54dbade4a840.PNG)

**Comment by hkjeffchan** [comment]
same as ionic3 on IOS13

**Comment by aparajita** [comment]
Hey @mhartington, I fixed this issue with this CSS:

```css
/*
  Push the top of the menu below the safe area
  so it doesn't overlay the status bar
*/
ion-menu {
  margin-top: env(safe-area-inset-top);
}

/*
  Pull the menu header up to account for the menu top margin
*/
ion-menu ion-header:first-child,
ion-menu ion-content:first-child {
  margin-top: calc(env(safe-area-inset-top) * -1);
}
```

**Comment by basvdijk** [comment]
> Hey @mhartington, I fixed this issue with this CSS:
> 
> ```css
> /*
>   Push the top of the menu below the safe area
>   so it doesn't overlay the status bar
> */
> ion-menu {
>   margin-top: env(safe-area-inset-top);
> }
> 
> /*
>   Pull the menu header up to account for the menu top margin
> */
> ion-menu ion-header:first-child,
> ion-menu ion-content:first-child {
>   margin-top: calc(env(safe-area-inset-top) * -1);
> }
> ```

@aparajita Thanks for providing a solution. I've tried to use the css without luck.

**Comment by paolosanchi** [comment]
it seems that the safe area is set for toolbar in header and footer:

https://github.com/ionic-team/ionic-framework/blob/f81d18c6f9f1bce056afda1cac4cf6d6ace0a7ca/core/src/components/header/header.scss#L17-L19
https://github.com/ionic-team/ionic-framework/blob/f81d18c6f9f1bce056afda1cac4cf6d6ace0a7ca/core/src/components/footer/footer.scss#L17-L19

So the supposed way to do it is this one:
```
<ion-app>
  <div class="ion-page" id="main"></div>
  <ion-menu contentId="main">
    <ion-header>
        <ion-toolbar>

        </ion-toolbar>
    </ion-header>
    <ion-content>

    </ion-content>
    <ion-footer>
        <ion-toolbar>

        </ion-toolbar>
    </ion-footer>
  </ion-menu>
</ion-app>
```

**Comment by SaroGFX** [comment]
I have spend countless hours now on trying to get this right. But the toolbar keeps getting screwing up in the menu. I tried a rebuild like above is done, but I still get bugged results. 

```JSX
<IonMenu 
      contentId="main" 
      swipeGesture={true} 
      disabled={isDisabled()}
      className={MenuCSS.Menu}
    >
      
      <IonHeader>
        <IonToolbar><IonTitle>Title</IonTitle></IonToolbar>
      </IonHeader>

      <nav>
        <IonText>Administration</IonText>
        <ul>
          <li>item</li>
          <li>item</li>
          <li>item</li>
          <li>item</li>
          <li>item</li>
          <li>item</li>
          <li>item</li>
          <li>last item</li>
        </ul>
      `</nav>`

      <footer>
        <IonText>Footer</IonText>
      </footer>
    </IonMenu>
```


```SCSS
ion-menu.Menu {
    --background: var(--wf-dark-gray);
    
    &::part(container) {
        justify-content: start;
    }

    nav {
        overflow-y: auto;
    }

    footer {
        margin-top: auto;
        background-color: rgba(var(--ion-color-white-rgb), 0.2);
        padding: 1em;
    }

}
```

The result on iPhone 13 

![Screenshot 2022-06-01 at 13 42 46](https://user-images.githubusercontent.com/3781800/171396654-f8e46560-d9f1-456b-a585-fc71bf8a32d1.png)

**Comment by eugr** [comment]
Looks like this bug has been open for 5 years already! Are there any plans to fix?

**Comment by thetaPC** [comment]
PR https://github.com/ionic-team/ionic-docs/pull/3102 does not fix this issue. This will be revisited at a later time.

**Comment by thetaPC** [comment]
Thank you for the issue!

When it comes to safe area, `ion-content` will not automatically apply padding to any of its sides to account for the [safe area](https://ionicframework.com/docs/theming/advanced#safe-area-padding). This is because the content component is often used in conjunction with other components that apply their own padding, such as [headers](https://ionicframework.com/docs/api/header) and [footers](https://ionicframework.com/docs/api/footer). However, if the content component is being used on its own, it may be desired to apply padding to the safe area.

In this case, a solution is to apply the padding directly to prevent any content from being rendered in the status bar.

```css
ion-menu ion-content::part(scroll) {
  padding-top: var(--ion-safe-area-top, 0);
}
```

You can read more about safe area padding at the [docs page](https://ionicframework.com/docs/api/content#safe-area-padding).

Thank you!
