### ISSUE TITLE
bug: popover alignment property renders incorrect location in frameworks

### ISSUE THREAD

**Issue by amandaejohnston** [ionic-team/ionic-framework#25337]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

When using various combinations of `side` and `alignment` on an inline `ion-popover`, the popover renders at the incorrect location when opened. This occurs in all three framework integrations (Angular/React/Vue), but *not* in core.

The linked repo has buttons for all combinations of `side` and `alignment`; here are the specific issues I noticed:

- `side="top"` shows the popover too low, overlapping the button. This occurs with all values of `alignment`, including when it isn't set at all.
![side top, alignment start](https://i.gyazo.com/334311600aca643d5d29b38e1f19186e.png)
- For `side`s of `right`, `left`, `start`, and `end`, and an `alignment` of `center`, the popover is rendered a pixel or two lower than the top edge of the button, when it should be vertically centered.
![side left, alignment center](https://i.gyazo.com/7a63d7eddb21bad14054f3646933cea8.png)
- For the same `side`s as the above, and an `alignment` of `end`, the popover is also rendered a few pixels lower than the button's top edge (slightly lower than with `alignment="center"`), when it should be raised higher so the bottom edges align.
![side left, alignment end](https://i.gyazo.com/aae73fd5c94e88cdd2bf41d3d2e5a0b3.png)

### Expected Behavior

Here are corresponding screenshots from the `position` test in core, which shows the correct behavior:

![side top, alignment start](https://i.gyazo.com/ce60599f3c46b15df5a9d01446225910.png)
![side left, alignment center](https://i.gyazo.com/e46891049da934763970087264432f4c.png)
![side left, alignment end](https://i.gyazo.com/5180e0641073e778048a0ac8e357820b.png)

### Steps to Reproduce

1. Clone repo (note the branch), `npm install`, `ionic serve`
2. Click buttons corresponding to described side/alignment values (headers list side, then alignment)

### Code Reproduction URL

https://github.com/amandaejohnston/sandbox-ionic-angular/tree/popover-positions

### Ionic Info

```
[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package'

       Require stack:
       - C:\Users\moogl\AppData\Roaming\npm\node_modules\@ionic\cli\lib\project\index.js
       - C:\Users\moogl\AppData\Roaming\npm\node_modules\@ionic\cli\lib\index.js
       - C:\Users\moogl\AppData\Roaming\npm\node_modules\@ionic\cli\index.js
       - C:\Users\moogl\AppData\Roaming\npm\node_modules\@ionic\cli\bin\ionic
[WARN] Error loading @capacitor/android package.json: Error: Cannot find module '@capacitor/android/package'

       Require stack:
       - C:\Users\moogl\AppData\Roaming\npm\node_modules\@ionic\cli\lib\project\index.js
       - C:\Users\moogl\AppData\Roaming\npm\node_modules\@ionic\cli\lib\index.js
       - C:\Users\moogl\AppData\Roaming\npm\node_modules\@ionic\cli\index.js
       - C:\Users\moogl\AppData\Roaming\npm\node_modules\@ionic\cli\bin\ionic

Ionic:

   Ionic CLI                     : 6.18.1 (C:\Users\moogl\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.1.6
   @angular-devkit/build-angular : 12.1.4
   @angular-devkit/schematics    : 12.2.14
   @angular/cli                  : 12.1.4
   @ionic/angular-toolkit        : 4.0.0

Capacitor:

   Capacitor CLI      : 3.3.3
   @capacitor/android : not installed
   @capacitor/core    : 3.3.3
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v16.13.0 (C:\Program Files\nodejs\node.exe)
   npm    : 8.1.0
   OS     : Windows 10
```

**Comment by corysmc** [comment]
Repro
https://stackblitz.com/edit/angular-ueypjw?file=src%2Fmain.tsx

This is still occurring in react (not core)
1. Visit the docs https://ionicframework.com/docs/api/popover#side-and-alignment-demo
2. Click the "react" as framework in demo space
3. Click the Stackblitz link
4. Notice the bug below:

BUG
<img width="388" alt="image" src="https://user-images.githubusercontent.com/6452188/185465138-8ac2b9de-7d37-40de-b551-c22ec4e27e99.png">

Should appear like it does in the docs
<img width="672" alt="image" src="https://user-images.githubusercontent.com/6452188/185465516-7c9b0023-4463-420d-aecd-044c4bb125b7.png">


Related issues: 
https://github.com/ionic-team/ionic-framework/issues/24780


For us this becomes a much larger issue because we're trying to display a list of options in an ion-popover - because it's a list - the items to select are pushed off the screen.
<img width="286" alt="image" src="https://user-images.githubusercontent.com/6452188/185469889-2b39753a-2a25-447d-8dd4-9fd5c37994f0.png">

The interesting thing here is that the caret is in the correct position - but but the content is not (The image below I modified the inline style to move the content up to show the caret)
<img width="422" alt="image" src="https://user-images.githubusercontent.com/6452188/185469692-6d7c8de9-0b09-4fe5-8617-48151a0073df.png">

**Comment by Lechevallier** [comment]
Is there a fix planned for the next release?
It's really annoying, I can't publish my app with this bug...
Any workaround?

**Comment by Lechevallier** [comment]
For the moment I found a work around fixing the popover to the top:
```
ion-popover::part(content) {
    top: 5vh;
}
```
At least it doesn't change position randomly...

**Comment by piotr-cz** [comment]
Seems that the `top` position when being calculated isn't reduced by popover content height somewhere [here](https://github.com/ionic-team/ionic-framework/blob/v6.3.0/core/src/components/popover/animations/md.enter.ts#L32)

**Comment by Lechevallier** [comment]
@piotr-cz yes, I investigated a bit as well:

Inspecting the popover element, it came out that it's the div with class `.popover-content` which gets the styling supposed to center it.
(In my app, my screen is 740x360, and the popover 250x296)
When it goes well, 32px is used, which is (360 - 296) / 2:
```css
top: calc(32px + var(--offset-y, 0px));
left: calc(245px + var(--offset-x, 0px));
transform-origin: left top;
```
When it goes wrong, 180px is used, which is (360 - 0) / 2:
```css
top: calc(180px + var(--offset-y, 0px));
left: calc(245px + var(--offset-x, 0px));
transform-origin: left top;
```
It's like it didn't got time to calculate the popover height 🤔 

This calcul is made by a function called `calculateWindowAdjustment`
https://github.com/ionic-team/ionic-framework/search?q=calculateWindowAdjustment

I didn't get further reading code.

**Comment by piotr-cz** [comment]
@Lechevallier As You have written, might be that the content of `.popover-content` element isn't visible at the time when calculation is being made and so it's dimensions are being retrieved as `0px x 0px`

**Comment by tekno0ryder** [comment]
I solved this issue by simply adding keepContentsMounted=true and it magically worked correctly!

**Comment by sean-perkins** [comment]
Hello everyone! Recently I addressed a different bug that logically overlaps with the behavior described here (https://github.com/ionic-team/ionic-framework/issues/24716). 

Can someone test with the `nightly` build and let me know if the problem continues to persist on your end?

```
npm install @ionic/angular@nightly
```

I have validated against the original reproduction and the issue appears to be resolved by my changes. 

The nightly changes that would address this would be available in the next patch release (6.3.7).

**Comment by Lechevallier** [comment]
Hi, good news!
I'm using react, will the fix be available for `@ionic/react` as well?
Thanks a lot

**Comment by tekno0ryder** [comment]
> Hello everyone! Recently I addressed a different bug that logically overlaps with the behavior described here (#24716).
> 
> Can someone test with the `nightly` build and let me know if the problem continues to persist on your end?
> 
> ```
> npm install @ionic/angular@nightly
> ```
> 
> I have validated against the original reproduction and the issue appears to be resolved by my changes.
> 
> The nightly changes that would address this would be available in the next patch release (6.3.7).

Thanks, but i tested on `"@ionic/react": "^6.3.7-nightly.20221115" ` still the issue exists and i have to use `keepContentMounted={true}` to work properly

**Comment by sean-perkins** [comment]
Hello everyone, thank you for the quick verification that that fix does not apply directly to all instances of this bug. 

Can you test this updated dev-build?

```
6.3.8-dev.11668625226.1db1de88
```

To install for a specific target, you will just apply:
```
npm install @ionic/react@6.3.8-dev.11668625226.1db1de88
```
 and replace `react` with `vue` or `angular`.

I've independently verified this change against local reproductions for Vue and React and it appears to correctly position the popover now. 

Thanks!

**Comment by tekno0ryder** [comment]
> ```
> npm install @ionic/react@6.3.8-dev.11668625226.1db1de88
> ```

Unfortunately still exists, sample code: [Stackblitz](https://stackblitz.com/edit/angular-zqsedm?file=package.json)

Change `keepContentMounted` to `true` to see how it should behave

**Comment by sean-perkins** [comment]
@tekno0ryder here is an updated version of your sample: https://stackblitz.com/edit/angular-zqsedm-ecuf7w?file=src%2Fmain.tsx

The `package-lock.json` was still resolving to `@ionic/core@6.3.7`, which does not contain the dev-build changes. This is just a quirk of Stackblitz; installing locally will resolve the correct package. 

Note: In my dev-build other overlays are broken. Don't use the dev-build outside of quick verification. I will post an updated dev-build that does not impact other overlays once CI passes.

**Comment by tekno0ryder** [comment]
> @tekno0ryder here is an updated version of your sample: https://stackblitz.com/edit/angular-zqsedm-ecuf7w?file=src%2Fmain.tsx
> 
> The `package-lock.json` was still resolving to `@ionic/core@6.3.7`, which does not contain the dev-build changes. This is just a quirk of Stackblitz; installing locally will resolve the correct package.
> 
> Note: In my dev-build other overlays are broken. Don't use the dev-build outside of quick verification. I will post an updated dev-build that does not impact other overlays once CI passes.

Thanks it works great 👏🏽

Btw even in my local machine I had to install the correct version for `@ionic/core`

**Comment by Lechevallier** [comment]
Thanks for the fix! 🙏 It works like a charm now 😃
