### ISSUE TITLE
bug: <ion-select> with interface="popover" not working using Chrome/114+

### ISSUE THREAD

**Issue by Akmalismail** [ionic-team/ionic-framework#27581]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v4.x, v5.x

### Current Behavior

Using `<ion-select>` with `interface="popover"` does not display the options, it only shows the backdrop.
I suspect this has something to do with Chrome's new [Popover API](https://developer.chrome.com/blog/new-in-chrome-114/#popover-api) released May 30 clashing with ionic framework.

Tested using ionic 4 and ionic 5

### Expected Behavior

Should display select with interface popover.

### Steps to Reproduce

1. Create ionic project from scratch and use `<ion-select>` component with `interface="popover"`.
2. Build and run on an android device using Chrome 114+.

### Code Reproduction URL

https://stackblitz.com/edit/ionic-angular-v5-template-blank-ts8baa

### Ionic Info

Ionic:

   Ionic CLI                     : 6.20.3 (C:\Users\Akmal\AppData\Roaming\nvm\v16.17.1\node_modules\@ionic\cli)
   Ionic Framework               : not installed
   @angular-devkit/build-angular : 16.0.3
   @angular-devkit/schematics    : 16.0.3
   @angular/cli                  : 16.0.3
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.0.4
   @capacitor/android : 5.0.4
   @capacitor/core    : 5.0.4
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.2

System:

   NodeJS : v16.17.1 (C:\Program Files\nodejs\node.exe)
   npm    : 8.19.2
   OS     : Windows 10

### Additional Information

I tested using `PopoverController` and it displays correctly.
There is also a Stack Overflow issue that uses ionic 6 
https://stackoverflow.com/questions/76376324/ion-select-popover-not-working-chrome-114

**Comment by ekzGuille** [comment]
Same for me. 
[This](https://stackoverflow.com/a/76381282) workaround solved the issue:

```css
[popover]:not(:popover-open):not(dialog[open]) {
    display: contents;
}
```

**Comment by NisStrom** [comment]
This was likely addressed in https://github.com/ionic-team/ionic-framework/issues/26643

**Comment by amandaejohnston** [comment]
Thank you for the report. Ionic v4 and v5 are no longer supported; see the [support table](https://ionicframework.com/docs/reference/support#framework-maintenance-and-support-status) for more details. Can you confirm if this bug occurs in the latest version of Ionic?

**Comment by Akmalismail** [comment]
> Thank you for the report. Ionic v4 and v5 are no longer supported; see the [support table](https://ionicframework.com/docs/reference/support#framework-maintenance-and-support-status) for more details. Can you confirm if this bug occurs in the latest version of Ionic?

No issue with latest ionic

**Comment by clov3r** [comment]
Bug is still present in ionic 6.7.4, symptoms are like in #26643 , but that fix does not seem to work for chrome 114

**Comment by amandaejohnston** [comment]
Thank you for the further details. Since the issue does not occur with the latest version of Ionic, I'm going to close this out as we are currently not making updates to v4 or v5, and v6 is only receiving critical or security fixes.

You can find a migration guide from Ionic v5 to v6 here: https://ionicframework.com/docs/updating/6-0
And v6 to v7 here: https://ionicframework.com/docs/updating/7-0
