### ISSUE TITLE
bug: Runtime errors on Android WebView after December 15, 2025 update - Array.prototype.at() not available and Cannot add property 0, object is not extensible in Shadow DOM

### ISSUE THREAD

**Issue by enrique-hg** [ionic-team/ionic-framework#30877]
### Prerequisites

- [x] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/docs/CONTRIBUTING.md#creating-an-issue).
- [x] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [x] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v8.x

### Current Behavior

After the **Android System WebView update on December 15, 2025** ([Google Play Store link](https://play.google.com/store/apps/details?id=com.google.android.webview&hl=es)), our Ionic React application started throwing two runtime errors that were not present before the update.

**This issue only affects Android 12 (API 31) and below.** Android 13+ devices are not affected.

**Error 1:** `TypeError: t.entries.at is not a function`

**Error 2:** `TypeError: Cannot add property 0, object is not extensible`
Cannot add property 0, object is not extensible
TypeError: Cannot add property 0, object is not extensible
at Array.push (<anonymous>)
at HTMLElement.createShadowRoot ([http://192.168.1.129:4000/static/js/](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.html)...)
at HTMLElement.__attachShadow ([http://192.168.1.129:4000/static/js/](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.html)...)
at new RouterOutlet ([http://192.168.1.129:4000/static/js/](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.html)...)
at createElement ([http://192.168.1.129:4000/static/js/](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.html)...)
at createInstance ([http://192.168.1.129:4000/static/js/](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.html)...)
at completeWork ([http://192.168.1.129:4000/static/js/](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.html)...)
at completeUnitOfWork ([http://192.168.1.129:4000/static/js/](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.html)...)
at performUnitOfWork ([http://192.168.1.129:4000/static/js/](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.html)...)
at workLoopSync ([http://192.168.1.129:4000/static/js/](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.html)...)

### Expected Behavior

The application should run without errors on Android WebView, as it did before the December 15, 2025 WebView update.

### Steps to Reproduce

1. Have Android System WebView updated to the latest version (December 15, 2025 update)
2. Use an Android device running **Android 12 or below**
3. Create/run an Ionic React application with `@ionic/react@8.x`
4. Run the application on the Android device
5. Observe the runtime errors in the console

### Code Reproduction URL

N/A - This occurs with standard Ionic React setup after the WebView update

### Ionic Info

Ionic:

@ionic/react: 8.6.0
@ionic/core: 8.6.2
@capacitor/core: 7.3.0
@capacitor/android: 7.3.0

Utility:

cordova-res: Not Installed
native-run: 2.0.1

System:

NodeJS: v20.9.0
npm: 10.x
OS: macOS

**Comment by enrique-hg** [comment]
<img width="437" height="926" alt="Image" src="https://github.com/user-attachments/assets/519db5e9-1569-4f25-a716-33134e204421" />

**Comment by ShaneK** [comment]
Hey! You say you're using Ionic v8.6.0 and this was fixed in v8.7.1. Please upgrade to at least v8.7.1 (or even the current version, 8.7.14) and try again.

**Comment by enrique-hg** [comment]
Thanks for the quick response! 

I've upgraded to `@ionic/react@8.7.12` and can confirm that **Error 2** (`Cannot add property 0, object is not extensible` in Shadow DOM) is now resolved. 

However, **Error 1** (`t.entries.at is not a function`) still persists after the upgrade. This error occurs on Android 13 and below after the December 15, 2024 WebView update.

It seems like some internal code is using `Array.prototype.at()` and other methods that are not available on older Android WebViews. Adding manual polyfills is not a viable solution since multiple methods appear to be missing at runtime.

Is this a known limitation, or should Ionic/Stencil include the necessary polyfills for older Android WebView versions?

**Current setup after upgrade:**
- `@ionic/react`: 8.7.12
- `@ionic/core`: 8.7.12
- Android 13 and below still affected by Error 1

**Comment by ShaneK** [comment]
@enrique-hg Hey! I cannot actually see us using `.at(` anywhere in our code base. Are you able to provide more information on where that might be coming from?
