### ISSUE TITLE
bug: In Android API 36, the safe-area is not respected.

### ISSUE THREAD

**Issue by Marius-Romanus** [ionic-team/ionic-framework#30900]
### Prerequisites

- [x] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/docs/CONTRIBUTING.md#creating-an-issue).
- [x] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [x] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v8.x

### Current Behavior

This is due to switching to Capacitor 8, which uses Android API 36, where `windowOptOutEdgeToEdgeEnforcement` no longer works:

https://capacitorjs.com/docs/apis/status-bar#android-16-behavior-change

Modals and popovers (that I've seen) are not respecting the safe area.

I've implemented the SystemBars plugin with `insetsHandling` in CSS, but it makes no difference:

https://capacitorjs.com/docs/apis/system-bars#android-note

It seems the only place where it's respected is the `top` element, if you have an `ion-header` in CSS:

```
ion-header ion-toolbar:first-of-type {
    padding-top: var(--ion-safe-area-top, 0);
}
```

I've tested it on the following emulators:

Pixel 9 Pro - API 36
Pixel 7 Pro - API 35
Pixel 6a - API 33

<img width="249" height="473" alt="Image" src="https://github.com/user-attachments/assets/57e19d6d-4d4a-46dc-8bd2-0bda15d18dc2" />
<img width="246" height="470" alt="Image" src="https://github.com/user-attachments/assets/f19186ea-28ac-44c6-be6e-cd2f8b3fc172" />

### Expected Behavior

The safe area should always be respected in all cases and at all edges.

### Steps to Reproduce

```
npm i
ionic capacitor build android
```
Enable "Navigation mode: Buttons" if it's set to "Gestures"
See the modal and popover in tab 1.

The global CSS contains:
```
html {
    --ion-safe-area-top: var(--safe-area-inset-top, env(safe-area-inset-top, 0px));
    --ion-safe-area-bottom: var(--safe-area-inset-bottom, env(safe-area-inset-bottom, 0px));
    --ion-safe-area-left: var(--safe-area-inset-left, env(safe-area-inset-left, 0px));
    --ion-safe-area-right: var(--safe-area-inset-right, env(safe-area-inset-right, 0px));
}
```

### Code Reproduction URL

https://github.com/Marius-Romanus/safe-area-ionic

### Ionic Info

```
Ionic:
   Ionic CLI: 7.2.1
   Ionic Framework: @ionic/angular 8.7.15
   @angular-devkit/build-angular: not installed
   @angular-devkit/schematics: 20.3.13
   @angular/cli: 21.0.4
   @ionic/angular-toolkit: 12.3.0

Capacitor:
   Capacitor CLI: 8.0.0
   @capacitor/android: 8.0.0
   @capacitor/core: 8.0.0
   @capacitor/ios: not installed

Utility:
   cordova-res: not installed globally
   native-run: 2.0.1

System:
   NodeJS: v24.11.0
   npm: 11.7.0
   OS: Windows 10
```

**Comment by ShaneK** [comment]
Hello! Thanks for your report. I actually have a PR up that addresses this here:
https://github.com/ionic-team/ionic-framework/pull/30889

Along with a dev build, if you'd like to try it. Please report any issues you find with the dev build or that solution there. Most of our team is OOO until the 5th, so it probably won't be in a patch release until the 7th at the earliest.

**Comment by ShaneK** [comment]
This is kind of a weird situation. Normally I'd close this as a duplicate, but the duplicate it's of is internal, and this was opened after the PR to fix it. So I guess I'll just update the PR to say it resolves this and it'll be closed when merged

**Comment by Marius-Romanus** [comment]
I tried version `8.7.16-dev.11767019759.14b7f2fa` and the same thing happens.

> Most of our team is OOO until the 5th, so it probably won't be in a patch release until the 7th at the earliest.

Happy holidays!

**Comment by ShaneK** [comment]
> I tried version `8.7.16-dev.11767019759.14b7f2fa` and the same thing happens.

Yeah, I was getting back to looking at this this morning and realized I was wrong, sorry. My PR was intended to address an issue with iOS. I'm gonna look into this as part of that solution though, since it's all pretty related.

**Comment by ShaneK** [comment]
@Marius-Romanus could you try my new dev buld, `8.7.16-dev.11767205737.13557925` and see if that works for you?

**Comment by Marius-Romanus** [comment]
Hi, it seems to work fine with the example, but it doesn't work in my actual project and I haven't figured out why yet.

**Edit:**
I think it has to do with the fact that in many cases I have it programmatically with controllers in different componentsand presentingElement when loading them:

`presentingElement: await this.modalController.getTop()`
or
`presentingElement: this.ionRouterOutlet.parentOutlet?.nativeEl`

```
modalController = inject(ModalController);
popoverController = inject(PopoverController);

this.modalController.create({ ...
this.popoverController.create({ ...
```

**Comment by ShaneK** [comment]
Could you try with this dev build?
```
8.7.16-dev.11767365495.141917e9
```

**Comment by Marius-Romanus** [comment]
Hi, it seems that in this version `8.7.16-dev.11767365495.141917e9` it doesn't display correctly at the top.

<img width="921" height="1044" alt="Image" src="https://github.com/user-attachments/assets/994e8538-e7dd-484b-8d5e-8b4a8d684433" />

And in my actual app, the bottom part still looks bad, and it jumps strangely between looking good and bad.

**Comment by ShaneK** [comment]
Can you please provide a reproduction of your app's setup that wasn't working with the previous implementation? It's pretty rough trying to troubleshoot this blind

**Comment by Marius-Romanus** [comment]
Of course :)

I've updated the project with a modal controller and a popover inside. You can see the error at the top there.

<img width="515" height="235" alt="Image" src="https://github.com/user-attachments/assets/2f6c1583-345c-41db-91d0-c8a8ee6d4e3a" />

I still haven't been able to figure out what the difference is between my actual project and the error at the bottom with the popover.

<img width="290" height="503" alt="Image" src="https://github.com/user-attachments/assets/ada549a5-6efa-4c3a-87b7-28a02b1dc9d0" />

https://github.com/Marius-Romanus/safe-area-ionic

**Comment by ShaneK** [comment]
Sorry, the previous dev build where you said it was working in the example but not in your app. I understand the latest dev build had issues, I was probably just gonna undo those changes and try again from the previous state if I could get a reproduction of those issues occuring

**Comment by Marius-Romanus** [comment]
I don't quite understand what you mean.

I've left the two buttons from the first example, which are inline.

And then I added another button using the "openModal()" controller, which looks wrong at the top in version: `8.7.16-dev.11767365495.141917e9`

I haven't been able to reproduce the issue of the popover with the controller at the bottom in the example, as it does in my actual application.

**Comment by ShaneK** [comment]
Okay, I think this dev build should help both issues. It's hard to reproduce the popover one on the emulator, but the idea behind my change that should fix it is changed safe area respect from checking to see if edges *touch* to seeing if the edge *overlaps* into the safe area. Additionally, the card modal on the first button's padding was missing because I didn't stop the check from thinking that the modal was a card modal (updated check checks mode now).

Here's the new dev build, let me know if this helps:
```
8.7.17-dev.11767641184.14a165bc
```

**Comment by Marius-Romanus** [comment]
The world of emulators, hehe. I tested it at pixel 9, API 36, and it seems to work fine in all the examples :)

However, there are some cases where the style isn't applied correctly...

Examples:
```
<div class="popover-content" part="content" style="bottom: calc(12px + var(--ion-safe-area-bottom, 0));top: calc(150px + var(--offset-y, 0px));left: calc(12px + var(--offset-x, 0px));transform-origin: left top;"><slot></slot></div>
element.style {
    bottom: calc(12px + var(--ion-safe-area-bottom, 0));
    top: calc(150px + var(--offset-y, 0px));
    left: calc(12px + var(--offset-x, 0px));
    transform-origin: left top;
}
```

Actual project, but I can't figure out what it is:
```
<div class="popover-content" part="content" style="bottom: 12px; top: calc(106px + var(--offset-y, 0px)); left: calc(150px + var(--offset-x, 0px)); transform-origin: right top;"><slot></slot></div>
element.style {
    bottom: 12px;
    top: calc(106px + var(--offset-y, 0px));
    left: calc(150px + var(--offset-x, 0px));
    transform-origin: right top;
}
```

**Comment by ShaneK** [comment]
haha well, back to shooting in the dark then. I *think* this one might do it, looks like I forgot to add the overlapping into the safe areas check to popovers:
```
8.7.17-dev.11767647939.17c197c2
```

**Comment by Marius-Romanus** [comment]
Nothing... it still doesn't work. I've been trying to figure out the difference between the two, and I can't see it. If you tell me how the bottom of the popover is determined, I might be able to figure it out.

**Comment by ShaneK** [comment]
The popover's positioning is mostly determined by this function as part of its animations:
https://github.com/ionic-team/ionic-framework/blob/7c197c2c99cb1bf245cbeeb94cadb41af0b8a40b/core/src/components/popover/utils.ts#L810

**Comment by Marius-Romanus** [comment]
The `^` in `package` played a trick on me. When I went to the function `const { originX, originY, top, left, bottom, checkSafeAreaTop, checkSafeAreaBottom } = calculateWindowAdjustment()`, I saw that it was outdated. Installing the exact version works correctly, but... I discovered another place where it's not working properly.

I updated the example project with a router link and a list inside:
```
{
    path: 'list',
    loadComponent: () => import('./list/list').then((c) => c.List),
  },
```
`<a routerLink="/list">Router List</a>`

In this case, it looks wrong both at the top and bottom.

<img width="510" height="948" alt="Image" src="https://github.com/user-attachments/assets/832a4f1d-7f94-4abc-abc5-676bb723c30e" />

**Comment by ShaneK** [comment]
> The ^ in package played a trick on me

Haha oh yeah, for sure. That's happened to me too more than once 😅 Something I knew I'd fixed once magically stopped working because of it haha

As for the new issue, you bring up a good point that safe areas were basically only there for headers and footers. My PR now adds safe area support for ion-pages without headers and footers, so as long as it's wrapped in an ion-page (which we generally expect most content to to have proper support), it should have safe area protections. New dev build:
```
8.7.17-dev.11767717752.14fe98a4
```

**Comment by Marius-Romanus** [comment]
I’m really putting you to work here 😅

When the header or footer is in a separate component, it's applying spacing, which it shouldn't.

<img width="730" height="383" alt="Image" src="https://github.com/user-attachments/assets/74023783-c090-40bc-a22e-7e101d3970d7" />

I've updated the example with a header in a separate component.

Strange things also happen when you rotate the phone.

<img width="1000" height="524" alt="Image" src="https://github.com/user-attachments/assets/168d7478-1891-4dab-9e3b-9484bfb45f7a" />

<img width="1004" height="483" alt="Image" src="https://github.com/user-attachments/assets/c55b3f42-2c3f-4d54-babd-f3b02d812148" />

<img width="1009" height="488" alt="Image" src="https://github.com/user-attachments/assets/cf509c97-618f-49b4-9cd3-eb68ad55df47" />

**Comment by ShaneK** [comment]
Hey! I've fixed a few issues, hopefully including both of those. Please give this dev build a shot:
```
8.7.17-dev.11767796972.148e4bc4
```

**Comment by Marius-Romanus** [comment]
Hi, I don't have time to give you an example right now, but I've seen cases where it still looks bad in the footer.

**Comment by ShaneK** [comment]
Hey! I'm not seeing any way to reproduce any issues with the footer, I'm afraid I'm gonna need more information to go on.

**Comment by Marius-Romanus** [comment]
I'm having trouble finding the examples because I'm not sure what values ​​they depend on. I'm trying to replicate what I have in my app to get them, but it doesn't always work, and I don't know why.

I've updated the example in tab 3 with a Kanban simulation.

<img width="377" height="236" alt="Image" src="https://github.com/user-attachments/assets/5fe0f805-9de8-4f89-bf1f-4601912d34f2" />

---

And in my actual app, which I haven't been able to replicate (I'm trying in tab 2 of the example), in the footer, but only in the first tab, it's adding the class "safe-area-bottom" to ion-content.

<img width="535" height="104" alt="Image" src="https://github.com/user-attachments/assets/7cdeff60-316d-484d-b631-c7c80eccd247" />

Here's the structure in case it helps: `body > app-root > ion-app > ion-router-outlet > app-dashboard > ion-tabs > div > ion-router-outlet > app-notes > ion-content`

---

And a simple list where the footer looks wrong, and I don't know why. I've also tried to replicate it in the example without success.

<img width="600" height="147" alt="Image" src="https://github.com/user-attachments/assets/204b1574-989e-4203-8464-6ba88a90bf23" />

Here's the structure in case it helps: `body > app-root > ion-app > ion-router-outlet > app-dashboard > ion-tabs > div > ion-router-outlet > app-labels > ion-content`

**Comment by ShaneK** [comment]
Edit: Don't use the one I just posted, there's some tests flagging issues I need to look at real quick

**Comment by ShaneK** [comment]
Okay, got all of that sorted! Please try again with this new dev build:
```
8.7.17-dev.11767897190.1ef0f479
```
There's so many edge cases in this one, sorry about how long it's taking

**Comment by Marius-Romanus** [comment]
Ugh, it was hard to reproduce. I think it's a reactivity issue.

First, sorry for the messy code I'm using in the demo. I'm having a hard time figuring out why things are happening, and I'm just trying things out randomly.

I created a route called `lists2` in the routes, at the same level as the tabs. In the tabs' HTML, I put an `if` statement that relies on a `signal computed()` function to check if the `routes` file contains the snapshot flag `data: { tabs: true }` to determine whether or not to display it.

Click on the link: Router List 2 and you'll see the error in the footer.

I think it's the cause of both the incorrect padding at the beginning and the missing padding in the list (as in the example).

<img width="658" height="208" alt="Image" src="https://github.com/user-attachments/assets/81fdbf0f-b0d5-41dd-a583-0f5984ad1339" />

<img width="668" height="151" alt="Image" src="https://github.com/user-attachments/assets/25842496-a942-45d5-96fe-41bb3d35584e" />

> There's so many edge cases in this one, sorry about how long it's taking

We make a good team 💪, it's always good to help the community. Updated demo :)

**Comment by ShaneK** [comment]
Hey! I see, looks like when tabs are hidden dynamically we need to re-check safe areas. I have a dev build here if you'd like to try it out:
```
8.7.17-dev.11767980394.1d9266a9
```

**Comment by Marius-Romanus** [comment]
Perfect! The only thing missing, I think, is adding the safe-area to the sides of ion-content when you lay the phone flat.

<img width="1001" height="497" alt="Image" src="https://github.com/user-attachments/assets/af32730c-510a-479d-9d2b-435d3839fd9c" />

**Comment by ShaneK** [comment]
Alright! I think this one should work. Here's the dev build:
```
8.7.17-dev.11767984108.1f9159e1
```

Please let me know how it goes!

**Comment by Marius-Romanus** [comment]
It seems that now in the lists, the padding extends further inwards.

<img width="1030" height="528" alt="Image" src="https://github.com/user-attachments/assets/9bb0535a-6bc3-42a8-b5a8-17ff0df95fdd" />

---

I understand that these kinds of style issues are separate from this particular problem and represent new features.

There are some design aspects that I imagine you'll have to improve in the future, for example, the progress bar... should it be cropped or expanded from side to side?

<img width="1006" height="279" alt="Image" src="https://github.com/user-attachments/assets/207aaa45-2ea1-41bc-86c8-6c1381017ab2" />

Also, it's noticeable that the maps often extend to the edge. I imagine you'll have to add a new option to `ion-content` to define whether you want them edge-to-edge or with padding, depending on your specific use case, such as when it's laid flat on both sides or if, for example, it doesn't have a footer or header.

<img width="137" height="513" alt="Image" src="https://github.com/user-attachments/assets/ecc40bb5-5ec7-4405-be7f-6759531b1804" />

<img width="265" height="588" alt="Image" src="https://github.com/user-attachments/assets/084b91b5-a5dc-43b6-87c9-1f441ddd99f3" />

**Comment by ShaneK** [comment]
Hey! I'm actually going to pull back on a lot of these changes because this has sort of spiraled into a series of unrelated changes to the original PR. I'm going to focus my PR on dealing with popovers and modals and we'll have to come back around at a later time to look at the other issues. I think some of these changes will require a bit more investigation than should be done for the patch I'm currently working on, unfortunately. So with these changes, I'd expect a lot of your concerns around modals and popovers to be fixed, but the other changes around unsupported safe areas will be undone for now to prevent unexpected issues with components that are already trying to support safe areas.

Here's the current dev build:
```
 8.7.17-dev.11768239180.18ee1069
```

I really appreciate you iterating on me with this and highlighting these issues. Sorry I wasn't able to get the other issues addressed at this time.

**Comment by Marius-Romanus** [comment]
Okay, perfect, I'll wait for the patch then to update my app

**Comment by Marius-Romanus** [comment]
Hi @ShaneK, is there any progress on this? Until it's working properly, we can't update to API 36.

**Comment by ShaneK** [comment]
Hey! Last week I merged this PR, which should address the popover and modal issues:
https://github.com/ionic-team/ionic-framework/pull/30949

**Comment by Marius-Romanus** [comment]
And any progress on tabs and ion-content?

**Comment by Marius-Romanus** [comment]
Hi again @ShaneK 

I've been testing everything again, with the latest version of everything, including `@ionic/angular: 8.8.1`, and it seems to work fine, except when it's a new route with an ion-header and an ion-content. 😬😬😬

**Edit:**

Okay... it wasn't the only place. I've seen another bug, two padding-bottom elements are being used in:

```
ion-modal>.ion-page {
    position: relative;
    contain: layout style;
    height: 100%;
}
<style>
[_nghost-ng-c2692105282] {
    padding-bottom: var(--ion-safe-area-bottom);
}
.ion-page {
    inset: 0;
    display: flex;
    position: absolute;
    flex-direction: column;
    justify-content: space-between;
    contain: layout size style;
    z-index: 0;
}
```

and bottom is added here:

`<div role="dialog" aria-modal="true" class="modal-wrapper ion-overlay-wrapper" part="content" style="height: calc(var(--height) - var(--ion-safe-area-bottom, 0px));padding-bottom: var(--ion-safe-area-bottom, 0px);"><slot></slot></div>`
